--- #YAML:1.0
name:                WebService-Livedoor-SpamChampuru-DNSBL
version:             0.01
abstract:            Perl interface of SpamChampuru DNSBL WebService
license:             ~
author:              
    - Kensuke Kaneko <k-kaneko@livedoor.jp>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    IO::Select:                    0
    Net::DNS:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
